# Generated by Django 5.2.2 on 2025-06-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artcategory",
            options={
                "verbose_name": "Категория произведения",
                "verbose_name_plural": "Категории произведения",
            },
        ),
        migrations.AlterModelOptions(
            name="artseries",
            options={
                "verbose_name": "Серия картины",
                "verbose_name_plural": "Серии картин",
            },
        ),
        migrations.AlterModelOptions(
            name="arttype",
            options={
                "verbose_name": "Тип рисовки",
                "verbose_name_plural": "Типы рисовки",
            },
        ),
        migrations.AlterModelOptions(
            name="mediacategory",
            options={
                "verbose_name": "Категория статьи",
                "verbose_name_plural": "Категории статей",
            },
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.mediacategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="mediacategory",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Категория статьи"),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата создания"),
        ),
    ]
