# Generated by Django 5.2.2 on 2025-06-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_artcategory_options_alter_artseries_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artitem",
            name="short_desc",
        ),
    ]
