# Generated by Django 5.2.2 on 2025-06-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_artitem_short_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artitem",
            name="tpe",
        ),
        migrations.DeleteModel(
            name="ArtType",
        ),
    ]
